// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#include <stdint.h>
#include "bg_gattdb_def.h"

#define GATT_HEADER(F) F
#define GATT_DATA(F) F
GATT_DATA(const uint16_t bg_gattdb_data_uuidtable_16_map [])=
{
    0x2800,
    0x2801,
    0x2803,
    0x1800,
    0x2a00,
    0x2a01,
    0x180a,
    0x2a29,
    0x1827,
    0x2adb,
    0x2adc,
    0x1828,
    0x2add,
    0x2ade,
    0x2901,
    0x1801,
    0x2a05,
    0x2b2a,
    0x2b29,
    0x2902,
};

GATT_DATA(const uint8_t bg_gattdb_data_uuidtable_128_map [])=
{
0xf0, 0x19, 0x21, 0xb4, 0x47, 0x8f, 0xa4, 0xbf, 0xa1, 0x4f, 0x63, 0xfd, 0xee, 0xd6, 0x14, 0x1d, 
0x63, 0x60, 0x32, 0xe0, 0x37, 0x5e, 0xa4, 0x88, 0x53, 0x4e, 0x6d, 0xfb, 0x64, 0x35, 0xbf, 0xf7, 
0x20, 0x67, 0x7a, 0x99, 0xa8, 0x0a, 0x0f, 0x8f, 0x72, 0x4e, 0x28, 0xdb, 0xea, 0xea, 0x93, 0xbf, 
0x20, 0xae, 0x70, 0x1a, 0xf2, 0x1b, 0x86, 0xa3, 0x57, 0x4a, 0xc6, 0x7c, 0x88, 0x7b, 0x54, 0x81, 
0x81, 0xd0, 0x0e, 0x95, 0x18, 0xca, 0x49, 0xb4, 0x7e, 0x41, 0x7d, 0x25, 0xfc, 0xa3, 0x2d, 0x9b, 
0x3a, 0x57, 0xee, 0x55, 0xae, 0xa7, 0xae, 0xba, 0x71, 0x4f, 0xe1, 0xfa, 0x18, 0x72, 0x8c, 0x41, 
0x36, 0x11, 0xcd, 0x5e, 0x06, 0xdf, 0xfb, 0xb2, 0xa9, 0x44, 0x13, 0x03, 0xa3, 0x50, 0x0b, 0xc6, 
0xe3, 0x1b, 0x9d, 0x13, 0x7d, 0x24, 0x07, 0x8e, 0xd8, 0x44, 0xcb, 0x2a, 0x61, 0xa5, 0x8a, 0xf3, 
0xa7, 0x75, 0xfc, 0xac, 0x29, 0x60, 0xb1, 0x80, 0xe3, 0x4d, 0x30, 0xcc, 0x90, 0x56, 0xc2, 0x95, 
0x24, 0x7d, 0xe1, 0x97, 0xae, 0xb5, 0xba, 0xb8, 0x61, 0x47, 0x40, 0xf7, 0xd6, 0xa2, 0x9e, 0x1e, 
0xdd, 0x76, 0xd5, 0x9d, 0x86, 0xbf, 0xa5, 0x95, 0x75, 0x4f, 0xe2, 0x06, 0xd2, 0xd9, 0xe6, 0x87, 
};




GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_53 ) = {
	.len=10,
	.data={0x53,0x75,0x62,0x5f,0x50,0x65,0x72,0x69,0x6f,0x64,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_data_attribute_field_52 ) = {
	.properties=0x0a,
	.index=15,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_51 ) = {
	.len=19,
	.data={0x0a,0x35,0x00,0xdd,0x76,0xd5,0x9d,0x86,0xbf,0xa5,0x95,0x75,0x4f,0xe2,0x06,0xd2,0xd9,0xe6,0x87,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_50 ) = {
	.len=20,
	.data={0x53,0x75,0x62,0x5f,0x44,0x65,0x73,0x74,0x69,0x6e,0x61,0x74,0x69,0x6f,0x6e,0x5f,0x41,0x64,0x64,0x72,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_data_attribute_field_49 ) = {
	.properties=0x0a,
	.index=14,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_48 ) = {
	.len=19,
	.data={0x0a,0x32,0x00,0x24,0x7d,0xe1,0x97,0xae,0xb5,0xba,0xb8,0x61,0x47,0x40,0xf7,0xd6,0xa2,0x9e,0x1e,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_47 ) = {
	.len=15,
	.data={0x53,0x75,0x62,0x5f,0x53,0x6f,0x75,0x72,0x63,0x65,0x5f,0x41,0x64,0x64,0x72,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_data_attribute_field_46 ) = {
	.properties=0x0a,
	.index=13,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_45 ) = {
	.len=19,
	.data={0x0a,0x2f,0x00,0xa7,0x75,0xfc,0xac,0x29,0x60,0xb1,0x80,0xe3,0x4d,0x30,0xcc,0x90,0x56,0xc2,0x95,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_44 ) = {
	.len=16,
	.data={0xe3,0x1b,0x9d,0x13,0x7d,0x24,0x07,0x8e,0xd8,0x44,0xcb,0x2a,0x61,0xa5,0x8a,0xf3,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_43 ) = {
	.len=6,
	.data={0x48,0x42,0x5f,0x54,0x54,0x4c,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_data_attribute_field_42 ) = {
	.properties=0x0a,
	.index=12,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_41 ) = {
	.len=19,
	.data={0x0a,0x2b,0x00,0x36,0x11,0xcd,0x5e,0x06,0xdf,0xfb,0xb2,0xa9,0x44,0x13,0x03,0xa3,0x50,0x0b,0xc6,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_40 ) = {
	.len=10,
	.data={0x50,0x75,0x62,0x5f,0x50,0x65,0x72,0x69,0x6f,0x64,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_data_attribute_field_39 ) = {
	.properties=0x0a,
	.index=11,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_38 ) = {
	.len=19,
	.data={0x0a,0x28,0x00,0x3a,0x57,0xee,0x55,0xae,0xa7,0xae,0xba,0x71,0x4f,0xe1,0xfa,0x18,0x72,0x8c,0x41,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_37 ) = {
	.len=9,
	.data={0x50,0x75,0x62,0x5f,0x43,0x6f,0x75,0x6e,0x74,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_data_attribute_field_36 ) = {
	.properties=0x0a,
	.index=10,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_35 ) = {
	.len=19,
	.data={0x0a,0x25,0x00,0x81,0xd0,0x0e,0x95,0x18,0xca,0x49,0xb4,0x7e,0x41,0x7d,0x25,0xfc,0xa3,0x2d,0x9b,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_34 ) = {
	.len=8,
	.data={0x50,0x75,0x62,0x5f,0x41,0x64,0x64,0x72,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_data_attribute_field_33 ) = {
	.properties=0x0a,
	.index=9,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_32 ) = {
	.len=19,
	.data={0x0a,0x22,0x00,0x20,0xae,0x70,0x1a,0xf2,0x1b,0x86,0xa3,0x57,0x4a,0xc6,0x7c,0x88,0x7b,0x54,0x81,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_31 ) = {
	.len=16,
	.data={0x20,0x67,0x7a,0x99,0xa8,0x0a,0x0f,0x8f,0x72,0x4e,0x28,0xdb,0xea,0xea,0x93,0xbf,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_data_attribute_field_30 ) = {
	.properties=0x08,
	.index=8,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_29 ) = {
	.len=19,
	.data={0x08,0x1f,0x00,0x63,0x60,0x32,0xe0,0x37,0x5e,0xa4,0x88,0x53,0x4e,0x6d,0xfb,0x64,0x35,0xbf,0xf7,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_28 ) = {
	.len=16,
	.data={0xf0,0x19,0x21,0xb4,0x47,0x8f,0xa4,0xbf,0xa1,0x4f,0x63,0xfd,0xee,0xd6,0x14,0x1d,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_data_attribute_field_26 ) = {
	.properties=0x10,
	.index=7,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_25 ) = {
	.len=5,
	.data={0x10,0x1b,0x00,0xde,0x2a,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_data_attribute_field_24 ) = {
	.properties=0x04,
	.index=6,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_23 ) = {
	.len=5,
	.data={0x04,0x19,0x00,0xdd,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_22 ) = {
	.len=2,
	.data={0x28,0x18,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_data_attribute_field_20 ) = {
	.properties=0x10,
	.index=5,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_19 ) = {
	.len=5,
	.data={0x10,0x15,0x00,0xdc,0x2a,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_data_attribute_field_18 ) = {
	.properties=0x04,
	.index=4,
	.max_len=0,
	.data=NULL,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_17 ) = {
	.len=5,
	.data={0x04,0x13,0x00,0xdb,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_16 ) = {
	.len=2,
	.data={0x27,0x18,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_15 ) = {
	.len=12,
	.data={0x53,0x69,0x6c,0x69,0x63,0x6f,0x6e,0x20,0x4c,0x61,0x62,0x73,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_14 ) = {
	.len=5,
	.data={0x02,0x10,0x00,0x29,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_13 ) = {
	.len=2,
	.data={0x0a,0x18,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_12 ) = {
	.len=2,
	.data={0x40,0x03,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_11 ) = {
	.len=5,
	.data={0x02,0x0d,0x00,0x01,0x2a,}
};
struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_10_data = {
	.len=20,
	.data={0x42,0x6c,0x75,0x65,0x47,0x65,0x63,0x6b,0x6f,0x20,0x4d,0x65,0x73,0x68,0x20,0x44,0x65,0x6d,0x6f,0x20,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_data_attribute_field_10 ) = {
	.properties=0x02,
	.index=3,
	.max_len=20,
	.data_varlen=&bg_gattdb_data_attribute_field_10_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_9 ) = {
	.len=5,
	.data={0x02,0x0b,0x00,0x00,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_8 ) = {
	.len=2,
	.data={0x00,0x18,}
};
uint8_t bg_gattdb_data_attribute_field_7_data[1]={0x00,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_data_attribute_field_7 ) = {
	.properties=0x0a,
	.index=2,
	.max_len=1,
	.data=bg_gattdb_data_attribute_field_7_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_6 ) = {
	.len=5,
	.data={0x0a,0x08,0x00,0x29,0x2b,}
};
uint8_t bg_gattdb_data_attribute_field_5_data[16]={0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_data_attribute_field_5 ) = {
	.properties=0x02,
	.index=1,
	.max_len=16,
	.data=bg_gattdb_data_attribute_field_5_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_4 ) = {
	.len=5,
	.data={0x02,0x06,0x00,0x2a,0x2b,}
};
uint8_t bg_gattdb_data_attribute_field_2_data[4]={0x00,0x00,0x00,0x00,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_data_attribute_field_2 ) = {
	.properties=0x20,
	.index=0,
	.max_len=4,
	.data=bg_gattdb_data_attribute_field_2_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_1 ) = {
	.len=5,
	.data={0x20,0x03,0x00,0x05,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_data_attribute_field_0 ) = {
	.len=2,
	.data={0x01,0x18,}
};
GATT_DATA(const struct bg_gattdb_attribute bg_gattdb_data_attributes_map[])={
    {.uuid=0x0000,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_0},
    {.uuid=0x0002,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_1},
    {.uuid=0x0010,.permissions=0x800,.caps=0x07,.datatype=0x01,.dynamicdata=&bg_gattdb_data_attribute_field_2},
    {.uuid=0x0013,.permissions=0x807,.caps=0x07,.datatype=0x03,.configdata={.flags=0x02,.index=0x00,.clientconfig_index=0x00}},
    {.uuid=0x0002,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_4},
    {.uuid=0x0011,.permissions=0x801,.caps=0x07,.datatype=0x01,.dynamicdata=&bg_gattdb_data_attribute_field_5},
    {.uuid=0x0002,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_6},
    {.uuid=0x0012,.permissions=0x803,.caps=0x07,.datatype=0x01,.dynamicdata=&bg_gattdb_data_attribute_field_7},
    {.uuid=0x0000,.permissions=0x801,.caps=0x04,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_8},
    {.uuid=0x0002,.permissions=0x801,.caps=0x04,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_9},
    {.uuid=0x0004,.permissions=0x801,.caps=0x04,.datatype=0x02,.dynamicdata=&bg_gattdb_data_attribute_field_10},
    {.uuid=0x0002,.permissions=0x801,.caps=0x04,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_11},
    {.uuid=0x0005,.permissions=0x801,.caps=0x04,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_12},
    {.uuid=0x0000,.permissions=0x801,.caps=0x04,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_13},
    {.uuid=0x0002,.permissions=0x801,.caps=0x04,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_14},
    {.uuid=0x0007,.permissions=0x801,.caps=0x04,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_15},
    {.uuid=0x0000,.permissions=0x801,.caps=0x01,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_16},
    {.uuid=0x0002,.permissions=0x801,.caps=0x01,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_17},
    {.uuid=0x0009,.permissions=0x804,.caps=0x01,.datatype=0x07,.dynamicdata=&bg_gattdb_data_attribute_field_18},
    {.uuid=0x0002,.permissions=0x801,.caps=0x01,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_19},
    {.uuid=0x000a,.permissions=0x800,.caps=0x01,.datatype=0x07,.dynamicdata=&bg_gattdb_data_attribute_field_20},
    {.uuid=0x0013,.permissions=0x807,.caps=0x01,.datatype=0x03,.configdata={.flags=0x01,.index=0x05,.clientconfig_index=0x01}},
    {.uuid=0x0000,.permissions=0x801,.caps=0x02,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_22},
    {.uuid=0x0002,.permissions=0x801,.caps=0x02,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_23},
    {.uuid=0x000c,.permissions=0x804,.caps=0x02,.datatype=0x07,.dynamicdata=&bg_gattdb_data_attribute_field_24},
    {.uuid=0x0002,.permissions=0x801,.caps=0x02,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_25},
    {.uuid=0x000d,.permissions=0x800,.caps=0x02,.datatype=0x07,.dynamicdata=&bg_gattdb_data_attribute_field_26},
    {.uuid=0x0013,.permissions=0x807,.caps=0x02,.datatype=0x03,.configdata={.flags=0x01,.index=0x07,.clientconfig_index=0x02}},
    {.uuid=0x0000,.permissions=0x801,.caps=0x04,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_28},
    {.uuid=0x0002,.permissions=0x801,.caps=0x04,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_29},
    {.uuid=0x8001,.permissions=0x802,.caps=0x04,.datatype=0x07,.dynamicdata=&bg_gattdb_data_attribute_field_30},
    {.uuid=0x0000,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_31},
    {.uuid=0x0002,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_32},
    {.uuid=0x8003,.permissions=0x803,.caps=0x07,.datatype=0x07,.dynamicdata=&bg_gattdb_data_attribute_field_33},
    {.uuid=0x000e,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_34},
    {.uuid=0x0002,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_35},
    {.uuid=0x8004,.permissions=0x803,.caps=0x07,.datatype=0x07,.dynamicdata=&bg_gattdb_data_attribute_field_36},
    {.uuid=0x000e,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_37},
    {.uuid=0x0002,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_38},
    {.uuid=0x8005,.permissions=0x803,.caps=0x07,.datatype=0x07,.dynamicdata=&bg_gattdb_data_attribute_field_39},
    {.uuid=0x000e,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_40},
    {.uuid=0x0002,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_41},
    {.uuid=0x8006,.permissions=0x803,.caps=0x07,.datatype=0x07,.dynamicdata=&bg_gattdb_data_attribute_field_42},
    {.uuid=0x000e,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_43},
    {.uuid=0x0000,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_44},
    {.uuid=0x0002,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_45},
    {.uuid=0x8008,.permissions=0x803,.caps=0x07,.datatype=0x07,.dynamicdata=&bg_gattdb_data_attribute_field_46},
    {.uuid=0x000e,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_47},
    {.uuid=0x0002,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_48},
    {.uuid=0x8009,.permissions=0x803,.caps=0x07,.datatype=0x07,.dynamicdata=&bg_gattdb_data_attribute_field_49},
    {.uuid=0x000e,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_50},
    {.uuid=0x0002,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_51},
    {.uuid=0x800a,.permissions=0x803,.caps=0x07,.datatype=0x07,.dynamicdata=&bg_gattdb_data_attribute_field_52},
    {.uuid=0x000e,.permissions=0x801,.caps=0x07,.datatype=0x00,.constdata=&bg_gattdb_data_attribute_field_53},
};

GATT_DATA(const uint16_t bg_gattdb_data_attributes_dynamic_mapping_map[])={
	0x0003,
	0x0006,
	0x0008,
	0x000b,
	0x0013,
	0x0015,
	0x0019,
	0x001b,
	0x001f,
	0x0022,
	0x0025,
	0x0028,
	0x002b,
	0x002f,
	0x0032,
	0x0035,
};

GATT_DATA(const uint8_t bg_gattdb_data_adv_uuid16_map[])={0x0};
GATT_DATA(const uint8_t bg_gattdb_data_adv_uuid128_map[])={0x0};
GATT_HEADER(const struct bg_gattdb_def bg_gattdb_data)={
    .attributes=bg_gattdb_data_attributes_map,
    .attributes_max=54,
    .uuidtable_16_size=20,
    .uuidtable_16=bg_gattdb_data_uuidtable_16_map,
    .uuidtable_128_size=11,
    .uuidtable_128=bg_gattdb_data_uuidtable_128_map,
    .attributes_dynamic_max=16,
    .attributes_dynamic_mapping=bg_gattdb_data_attributes_dynamic_mapping_map,
    .adv_uuid16=bg_gattdb_data_adv_uuid16_map,
    .adv_uuid16_num=0,
    .adv_uuid128=bg_gattdb_data_adv_uuid128_map,
    .adv_uuid128_num=0,
    .caps_mask=0x07,
    .enabled_caps=0x00,
};

const struct bg_gattdb_def *bg_gattdb=&bg_gattdb_data;
